# Generated by Django 3.2.16 on 2022-10-19 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('human_resource', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производителей',
            },
        ),
        migrations.CreateModel(
            name='TechType',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Тип оборудования')),
                ('inventCode', models.CharField(default='00', max_length=20, verbose_name='Инвентаризационный префикс')),
            ],
            options={
                'verbose_name': 'Тип оборудования',
                'verbose_name_plural': 'Типы оборудования',
            },
        ),
        migrations.CreateModel(
            name='TechModel',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Модель')),
                ('manufacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invent.manufacture', verbose_name='Производитель')),
                ('modeltype', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='invent.techtype', verbose_name='Тип устройства')),
            ],
            options={
                'verbose_name': 'Модель оборудования',
                'verbose_name_plural': 'Модели оборудования',
            },
        ),
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('inventNumber', models.CharField(max_length=100, unique=True, verbose_name='Инвентаризационный номер')),
                ('serialNumber', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Серийный номер')),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.employer', verbose_name='Ответсвенный сотрудник')),
                ('modelTech', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='invent.techmodel', verbose_name='Модель устройства')),
            ],
            options={
                'verbose_name': 'Журнал Оборудования',
                'verbose_name_plural': 'Журнал Оборудования',
            },
        ),
    ]
