# Generated by Django 3.2.16 on 2022-10-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacture',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterModelOptions(
            name='techmodel',
            options={'verbose_name': 'Оборудование', 'verbose_name_plural': 'Оборудование'},
        ),
        migrations.AlterField(
            model_name='tech',
            name='inventNumber',
            field=models.CharField(max_length=100, verbose_name='Инвентаризационный номер'),
        ),
    ]
